version: "3.8"

services:
  web_server:
    build: .
    container_name: web_server_container
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/test?directConnection=true"

  mongodb:
    image: mongo:7.0.8-jammy
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
